<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <div>
    <label><?php echo $this->__('Seu CEP') ?>*</label>
    <span>
      <input type="text" title="<?php echo $this->__('Seu CEP') ?>" name="payment[cep_destino]" value="<?php echo $this->htmlEscape($this->getInfoData('cep_destino')) ?>" />
    </span>
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
